name: Upload Website

on:
  push:
    branches:
    - main
    
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Set Env
      run: |
        echo "${{ secrets.ENV_PROD }}" >> .env   
    - name: Build App
      run: |
        npm install && npm run build && ls *
      env:
        CI: ""
    - name: Copy to S3          
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        # NODE_ENV: development # optional: defaults to production
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_PROD }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ap-southeast-1 # optional: defaults to us-east-1
        SOURCE_DIR: build # optional: defaults to public
